// Generated by https://quicktype.io

export interface JSONData {
    technologies: Technology[];
    all_courses: AllCourses[];
}

export interface AllCourses {
    _id : string;
    code: string;
    name: string;
}

export interface SmallCourses {
    code: string;
    name: string;
}

export interface Technology {
    _id: string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     Course[];
}

export interface Course {
    code: string;
    name: string;
}

export interface ViewProps {
    technologies: Technology[];
    all_courses: AllCourses[];
    visible: boolean;
}
